### PR TITLE
Correct indexing into k during scalarmult

### PR DESCRIPTION
**Pull request by brycx**

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks!

That's a side effect of having an ambiguous `to_bytes()` function that doesn't say anything about endianness.

**Comment by jedisct1** [comment]
Mmmm that doesn't seen to be enough. The ECDSA verification test  is now failing, so there might be another endianness issue.

**Comment by brycx** [comment]
Yeah, the doctest is still failing. Currently looking at this from `ecdsa` crate because (`hazmat.rs` L196) of the `verify_prehashed()` func:

```
let z = Scalar::<C>::from_be_bytes_reduced(z);
```

**Comment by jedisct1** [comment]
Found it.

`fiat_p384_scalar_from_bytes()` expects the scalar to be in little-endian, so `Scalar::from_be_byte()` should swap the bytes prior to calling it.

**Comment by jedisct1** [comment]
Maybe the crate should internally use little endian everywhere to represent scalars, if only for consistency with Zig's reference code. There's no point in using big endian on modern architectures.

**Comment by brycx** [comment]
> fiat_p384_scalar_from_bytes() expects the scalar to be in little-endian, so Scalar::from_be_byte() should swap the bytes prior to calling it.

https://github.com/jedisct1/rust-p384/blob/8cfaa5dd3ce87489cd5966f1b441b7fb63db9af6/src/arithmetic/scalar.rs#L558

Yeah, this seems to be a case as well, though swapping still leaves `.verify()` failing (unless there's multiple cases of this).

**Comment by brycx** [comment]
> (unless there's multiple cases of this).

Based on the new commits, I see you found the rest. ECDSA passes for me now!

**Comment by jedisct1** [comment]
Done. Everything is now internally in LE, and we have `{from|to}_{be|le}_bytes()` for conversion with explicit endianness.

**Comment by jedisct1** [comment]
Note that  all the `from_*` functions currently don't verify that the input is in canonical form. They should.

**Pull request merged**
